### ISSUE TITLE
There's a problem with the packaging

### ISSUE THREAD

**Issue by ganiserb** [gbourdin/totango-python#2]
Hi Germán!

Whenever I try to install via `pip install totango==0.3.2` I get the following error:

```
Collecting totango
  Downloading https://files.pythonhosted.org/packages/80/2a/08167d95e128d03cf6f12d9a66c77ac02820622518116d3e676f6e99393f/totango-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yt8alY/totango/setup.py", line 28, in <module>
        long_description='%s\n%s' % (read('README.rst'), re.sub(':[a-z]+:`~?(.*?)`', r'``\1``', read('CHANGELOG.rst'))),
      File "/tmp/pip-install-yt8alY/totango/setup.py", line 12, in read
        encoding=kwargs.get('encoding', 'utf8')
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-yt8alY/totango/CHANGELOG.rst'
```

Installing from GitHub works though:

```
$> pip install git+https://github.com/gbourdin/totango-python.git@0.3.2      
Collecting git+https://github.com/gbourdin/totango-python.git@0.3.2
  Cloning https://github.com/gbourdin/totango-python.git (to revision 0.3.2) to /tmp/pip-req-build-FU6MIV
Requirement already satisfied: requests in /home/gabriel/.virtualenvs/d/lib/python2.7/site-packages (from totango==0.3.2) (2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/gabriel/.virtualenvs/d/lib/python2.7/site-packages (from requests->totango==0.3.2) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in /home/gabriel/.virtualenvs/d/lib/python2.7/site-packages (from requests->totango==0.3.2) (2018.8.24)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/gabriel/.virtualenvs/d/lib/python2.7/site-packages (from requests->totango==0.3.2) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/gabriel/.virtualenvs/d/lib/python2.7/site-packages (from requests->totango==0.3.2) (2.8)
Building wheels for collected packages: totango
  Building wheel for totango (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-7G4KSM/wheels/c0/09/1a/304a669c775cdd2fca71dcedd546b6a5ab86fd77a8ac80dd51
Successfully built totango
Installing collected packages: totango
Successfully installed totango-0.3.2

```

**Comment by letoss** [comment]
I need this fixed for my project too!

**Comment by gbourdin** [comment]
Interesting, looks like it was working up until recently thought, right?

It's likely something about packaging or how this is downloaded for install changed. Would you mind creating a PR with a proposed changeset @ganiserb ?

I think I'll be able to address this in a week or two otherwise.

**Comment by gbourdin** [comment]
Took more than a few weeks but this is now fixed and I've added compatibility for modern Python.
